import fs from "node:fs";

const dir = "docs/full-website-gap-audit-2026-08-05";
const pages = JSON.parse(
  fs.readFileSync(`${dir}/crawl-data/pages.json`, "utf8"),
) as Array<{
  path: string;
  status: number;
  wordCount: number;
  title: string;
}>;

function actionFor(path: string, wc: number, status: number): string {
  if (status === 404) return "Keep";
  if (path === "/เกี่ยวกับเรา" || path === "/ติดต่อ") return "Rewrite";
  if (path === "/คำถามที่พบบ่อย") return "Improve";
  if (path.includes("/บทความ/") && path !== "/บทความ" && wc < 400) return "Rewrite";
  if (path.includes("/พื้นที่/") && wc < 400) return "Improve";
  if (
    path.includes("/นโยบาย") ||
    path.includes("/ข้อกำหนด") ||
    path === "/นโยบายรับซื้อสินค้าและการยืนยันเจ้าของ"
  ) {
    return wc < 200 ? "Improve" : "Keep";
  }
  if (path.includes("รับซื้อ") || path.includes("บริการ") || path.includes("ส่ง") || path.includes("วิธี")) {
    return "Keep";
  }
  return "Keep";
}

function reason(action: string, path: string, wc: number): string {
  if (action === "Rewrite" && path.includes("บทความ")) return "Thin article; deepen for AEO";
  if (action === "Rewrite") return "Entity/trust alignment with Ubon HQ brief";
  if (action === "Improve" && path.includes("พื้นที่")) return "Thin area; add logistics or merge later";
  if (action === "Improve") return "Expand unique helpful content";
  return "Meets current intent; maintain";
}

const pageRows = [
  "url_path,status,word_count,action,priority,primary_issue,notes",
];
for (const p of pages) {
  const act = actionFor(p.path, p.wordCount, p.status);
  const pri =
    act === "Rewrite" && (p.path === "/เกี่ยวกับเรา" || p.path === "/ติดต่อ")
      ? "P1"
      : act === "Rewrite" || act === "Improve"
        ? "P2"
        : "P3";
  pageRows.push(
    [
      `"${p.path}"`,
      p.status,
      p.wordCount,
      act,
      pri,
      `"${reason(act, p.path, p.wordCount)}"`,
      `"${(p.title || "").replaceAll('"', "'")}"`,
    ].join(","),
  );
}
fs.writeFileSync(`${dir}/14-page-action-matrix.csv`, pageRows.join("\n"), "utf8");

const findings = [
  [
    "finding_id",
    "severity",
    "category",
    "url_or_file",
    "evidence",
    "impact",
    "root_cause",
    "recommendation",
    "effort",
    "expected_impact",
    "test_after_fix",
  ].join(","),
  [
    "F-001",
    "P1",
    "Local SEO / E-E-A-T",
    "/เกี่ยวกับเรา;/ติดต่อ;src/data/site.ts",
    "Brief requires Ubon store; production homepage has 0 Ubon mentions; no Maps",
    "Entity mismatch; weaker local trust and AI citations",
    "Site scoped as Korat service area without HQ NAP",
    "Publish verified Ubon NAP/hours/Maps; clarify Korat as service area not branch",
    "M",
    "High",
    "About/Contact show address; LocalBusiness validates; no false branch claims",
  ].join(","),
  [
    "F-002",
    "P1",
    "Analytics",
    "src/layouts/BaseLayout.astro; production HTML",
    "winner_cta dispatched; no gtag/GTM/G- ID on homepage",
    "Cannot attribute LINE/phone conversions to pages",
    "Event bus without analytics sink",
    "Add GA4 + Consent Mode; map winner_cta to events without PII",
    "M",
    "High",
    "DebugView shows line/phone events; consent gates tags",
  ].join(","),
  [
    "F-003",
    "P1",
    "UX/CRO",
    "sitewide",
    "crawl hasFB=false all pages; no facebook.com links on homepage",
    "Misses brief conversion channel",
    "Facebook URL never added to site config",
    "Add Facebook CTA when official page URL confirmed",
    "S",
    "Medium",
    "FB link present header/footer/sticky; click event fires",
  ].join(","),
  [
    "F-004",
    "P1",
    "Local SEO",
    "schema.ts; crawl hasMaps=false",
    "Organization only; no LocalBusiness/Store; no Maps",
    "Poor Maps pack / knowledge corroboration",
    "Deliberate no-store stance for Korat without HQ publish",
    "Add LocalBusiness for Ubon only with on-page address match",
    "M",
    "High",
    "Rich Results / schema validator; NAP match GBP",
  ].join(","),
  [
    "F-005",
    "P1",
    "GEO / Entity",
    "/เกี่ยวกับเรา",
    "About denies Korat store; omits Ubon HQ",
    "AI/search may under-trust physical business",
    "Content policy incomplete vs business brief",
    "Rewrite About with verified HQ facts + service-area wording",
    "M",
    "High",
    "About mentions Ubon HQ + Korat service; no branch claim",
  ].join(","),
  [
    "F-006",
    "P1",
    "Deployment identity",
    "git; Vercel",
    "Local ahead 1 of origin; production SHA not re-proven this session",
    "Risk of docs/code drift confusion before next deploy",
    "Docs commits + no Vercel API check",
    "Confirm Vercel deployment commit; sync origin; avoid dirty deploys",
    "S",
    "Medium",
    "origin/main==deployed SHA for content commits",
  ].join(","),
  [
    "F-007",
    "P1",
    "Measurement / GSC",
    "GSC",
    "Prior audits: GSC unavailable; still NOT PROVEN",
    "Blind to index coverage and CWV field data",
    "Property access / verification gap",
    "Verify Search Console; submit sitemap; export coverage",
    "S",
    "High",
    "Sitemap fetched; coverage export archived",
  ].join(","),
  [
    "F-008",
    "P2",
    "Content",
    "14 thin URLs in crawl-summary",
    "Articles/areas wordCount<400",
    "Weak AEO/snippets; doorway risk on amphoe",
    "Short templates",
    "Rewrite thin articles; improve or merge thin areas",
    "L",
    "Medium",
    "Re-crawl wc; no new doorway provinces",
  ].join(","),
  [
    "F-009",
    "P2",
    "Security",
    "response headers",
    "CSP/XCTO/XFO/Referrer/Permissions null; HSTS present",
    "Clickjacking/MIME sniffing residual risk",
    "Headers not set in vercel.json",
    "Add security headers; report-only CSP first",
    "S",
    "Medium",
    "securityheaders.com or curl shows headers",
  ].join(","),
  [
    "F-010",
    "P2",
    "CRO",
    "sitewide forms",
    "No on-site valuation form",
    "Friction for users avoiding LINE",
    "LINE-only funnel by design",
    "MVP form with photo upload + non-PII analytics",
    "L",
    "High",
    "Submit success path; spam protection; privacy notice",
  ].join(","),
  [
    "F-011",
    "P2",
    "AEO",
    "/คำถามที่พบบ่อย",
    "wordCount~219",
    "Weak FAQ hub for AI Overviews",
    "Stub page",
    "Expand real customer FAQs matching on-page + schema",
    "M",
    "Medium",
    "FAQ count>=8; schema matches visible Q&A",
  ].join(","),
  [
    "F-012",
    "P2",
    "Content / CRO",
    "/วิธีประเมินราคา",
    "Competitors show price ranges; this domain lighter on ranges",
    "Lower commercial investigation satisfaction",
    "Avoid overclaim historically",
    "Add dated reference ranges with strong disclaimer",
    "M",
    "High",
    "Ranges visible; disclaimer present; no guarantee claims",
  ].join(","),
  [
    "F-013",
    "P2",
    "Privacy",
    "cookie policy",
    "No cookie policy page",
    "Compliance gap when tags added",
    "No non-essential cookies yet",
    "Add cookie policy with GA launch",
    "S",
    "Medium",
    "Linked from footer + consent UI",
  ].join(","),
  [
    "F-014",
    "P2",
    "Internal linking",
    "articles → money",
    "Contextual links inconsistent",
    "Missed equity to money pages",
    "Template CTA only",
    "Add 1-2 contextual links per article to matching services",
    "M",
    "Medium",
    "Crawl shows increased inlinks to hubs",
  ].join(","),
  [
    "F-015",
    "P2",
    "Local SEO",
    "/พื้นที่/* thin",
    "4 amphoe pages <400 words",
    "Doorway-adjacent risk",
    "Template locality pages",
    "Add unique logistics or merge into city hub",
    "M",
    "Medium",
    "Either unique content or 301 to hub",
  ].join(","),
  [
    "F-016",
    "P2",
    "Technical SEO",
    "Twitter metadata",
    "Not systematically verified sitewide",
    "Weaker social previews",
    "OG prioritized over Twitter tags",
    "Ensure twitter:card on BaseLayout",
    "S",
    "Low",
    "Meta present on sample pages",
  ].join(","),
  [
    "F-017",
    "P2",
    "Performance",
    "Field CWV",
    "PSI 429; GSC CWV unavailable",
    "Cannot prove CWV competitiveness",
    "Tooling limits this session",
    "Collect lab+field baselines next sprint",
    "M",
    "Medium",
    "CrUX/GSC shows Good or plan fixes",
  ].join(","),
  [
    "F-018",
    "P2",
    "E-E-A-T",
    "photos/reviews",
    "No storefront/team/transaction photos on site",
    "Lower trust vs walk-in competitors",
    "Asset not published",
    "Publish real photos only; GBP reviews program",
    "M",
    "High",
    "About/Contact media gallery live",
  ].join(","),
  [
    "F-019",
    "P2",
    "Analytics false positive",
    "gap-audit-crawl.ts hasGA",
    "hasGA true but HTML has no GA",
    "Audit noise",
    "Regex too broad",
    "Fix detector in future tooling (report-only now)",
    "S",
    "Low",
    "hasGA false without tags",
  ].join(","),
  [
    "F-020",
    "P2",
    "Legal pages depth",
    "/ข้อกำหนดการใช้บริการ",
    "wc~120",
    "Thin legal/trust page",
    "Short stub",
    "Expand essential terms without legalese spam",
    "S",
    "Low",
    "wc and counsel review",
  ].join(","),
  [
    "F-021",
    "P3",
    "UX",
    "CTA repetition",
    "Multiple identical LINE CTAs per page",
    "Mild fatigue",
    "Aggressive CRO pattern",
    "Vary labels; keep sticky",
    "S",
    "Low",
    "User test mobile scroll",
  ].join(","),
  [
    "F-022",
    "P3",
    "A11y",
    "keyboard/contrast",
    "Full a11y pass NOT PROVEN",
    "Unknown WCAG gaps",
    "Audit scope limited",
    "Run axe/keyboard pass",
    "M",
    "Low",
    "Critical a11y issues=0",
  ].join(","),
  [
    "F-023",
    "P3",
    "Tech",
    "PWA manifest",
    "Manifest NOT PROVEN",
    "Minor",
    "Not required for SEO",
    "Optional web manifest",
    "S",
    "Low",
    "manifest linked if added",
  ].join(","),
  [
    "F-024",
    "P3",
    "Content",
    "author bylines",
    "Organization-only authors",
    "Weaker Experience signals",
    "No person entities",
    "Add editor/ops reviewer where real",
    "S",
    "Low",
    "Article shows reviewer name",
  ].join(","),
  [
    "F-025",
    "P3",
    "Ops",
    "untracked audit scripts",
    "scripts/gap-audit-*.ts untracked",
    "Process clutter",
    "Audit tooling not committed",
    "Decide keep in repo or gitignore after review",
    "S",
    "Low",
    "Clean git status policy",
  ].join(","),
  [
    "F-026",
    "P3",
    "Visual QA",
    "tablet viewport",
    "No 768 screenshots",
    "Tablet layout NOT PROVEN",
    "Capture matrix limited",
    "Add tablet screenshots next audit",
    "S",
    "Low",
    "768 captures archived",
  ].join(","),
  [
    "F-027",
    "P3",
    "Dependencies",
    "npm audit",
    "Not run this session",
    "Unknown CVE exposure",
    "Scope limit",
    "Run npm audit in CI",
    "S",
    "Low",
    "High vulns triaged",
  ].join(","),
  [
    "F-028",
    "P3",
    "Indexing ops",
    "legacy URLs",
    "GSC 404 legacy list NOT PROVEN",
    "Possible missed redirects",
    "No coverage export",
    "Export GSC Not Found; add redirects as needed",
    "M",
    "Medium",
    "Top legacy 404s redirected",
  ].join(","),
  [
    "O-001",
    "Opportunity",
    "Content",
    "/ตัวอย่างช่วงราคารับซื้อ",
    "Competitor price tables",
    "Higher conversion intent coverage",
    "Missing first-party ranges",
    "Create dated ranges with disclaimer",
    "M",
    "High",
    "Page indexed; CTA clicks up",
  ].join(","),
  [
    "O-002",
    "Opportunity",
    "Content",
    "ขายขาด vs ฝากขาย",
    "Competitor consign angles",
    "Capture alternate intent IF service real",
    "Service not documented on this domain",
    "Create only with real process",
    "M",
    "Medium",
    "No false service claims",
  ].join(","),
  [
    "O-003",
    "Opportunity",
    "CRO",
    "valuation form MVP",
    "LINE-only funnel",
    "Recover non-LINE users",
    "Design choice",
    "Build form + spam protection",
    "L",
    "High",
    "Successful submissions tracked",
  ].join(","),
  [
    "O-004",
    "Opportunity",
    "E-E-A-T",
    "case studies",
    "No first-party cases",
    "GEO differentiation",
    "Assets not written",
    "Publish anonymized real cases",
    "M",
    "Medium",
    "2-3 cases live",
  ].join(","),
  [
    "O-005",
    "Opportunity",
    "AEO",
    "comparison tables",
    "Limited tables",
    "Snippet eligibility",
    "Prose-heavy pages",
    "Add compare sell-in-store vs ship vs pickup",
    "S",
    "Medium",
    "Table present on how-to page",
  ].join(","),
  [
    "O-006",
    "Opportunity",
    "Internal linking",
    "topic clusters",
    "Cluster incomplete",
    "Topical authority",
    "Growth stage",
    "Systematically link device+condition+article triads",
    "M",
    "Medium",
    "Cluster map documented",
  ].join(","),
  [
    "O-007",
    "Opportunity",
    "Local",
    "GBP optimization",
    "GBP access NOT PROVEN",
    "Maps pack",
    "Off-site asset",
    "Complete GBP services/photos/Q&A",
    "M",
    "High",
    "GBP complete checklist",
  ].join(","),
  [
    "O-008",
    "Opportunity",
    "Content",
    "Ubon service clarity page",
    "HQ not on domain",
    "Entity clarity",
    "Pending verified address",
    "After NAP verified, dedicated store page",
    "M",
    "High",
    "No doorway provinces auto-created",
  ].join(","),
  [
    "O-009",
    "Opportunity",
    "Tech",
    "AI bot policy docs",
    "Allow-all only",
    "Governance",
    "No explicit AI policy",
    "Document intentional AI crawl policy",
    "S",
    "Low",
    "Policy page or robots comments",
  ].join(","),
  [
    "O-010",
    "Opportunity",
    "CRO",
    "photo examples UI",
    "Checklist text exists; visual examples limited",
    "Better submission quality",
    "Text-only guidance",
    "Add example photo grid",
    "S",
    "Medium",
    "Examples on valuation page",
  ].join(","),
  [
    "O-011",
    "Opportunity",
    "Content",
    "broken device cluster",
    "Pages exist; deepen",
    "High-intent damaged device queries",
    "Depth variance",
    "Expand unique diagnostics tips",
    "M",
    "Medium",
    "Unique sections per condition page",
  ].join(","),
  [
    "O-012",
    "Opportunity",
    "Analytics",
    "scroll/404 events",
    "Absent",
    "Funnel diagnosis",
    "No tag manager",
    "Add after GA foundation",
    "S",
    "Low",
    "Events visible in GA4",
  ].join(","),
  [
    "O-013",
    "Opportunity",
    "Security",
    "rate limit forms",
    "N/A until form",
    "Spam resilience",
    "No form yet",
    "Turnstile/hCaptcha on form launch",
    "S",
    "Medium",
    "Spam submissions blocked",
  ].join(","),
  [
    "O-014",
    "Opportunity",
    "Content",
    "cookie + privacy deepen",
    "Privacy exists; thin legal siblings",
    "Trust/compliance",
    "Minimal legal copy",
    "Counsel-approved expansion",
    "M",
    "Low",
    "Pages updated",
  ].join(","),
  [
    "O-015",
    "Opportunity",
    "GEO",
    "sameAs social entities",
    "Organization schema lacks sameAs",
    "Entity graph",
    "Not implemented",
    "Add sameAs for LINE/FB/GBP when URLs confirmed",
    "S",
    "Medium",
    "schema sameAs populated",
  ].join(","),
  [
    "O-016",
    "Opportunity",
    "Performance",
    "third-party budget",
    "Currently clean",
    "Protect INP when tags added",
    "Future risk",
    "Tag governance checklist",
    "S",
    "Medium",
    "INP remains Good after tags",
  ].join(","),
  [
    "O-017",
    "Opportunity",
    "Content",
    "how to verify seller legitimacy",
    "Missing educational trust page",
    "Differentiator vs shady buyers",
    "Not written",
    "Publish checklist aligned to real process",
    "M",
    "Medium",
    "Article live + internal links",
  ].join(","),
  [
    "O-018",
    "Opportunity",
    "CRO",
    "response-time SLA copy",
    "Avoid overclaim",
    "Expectation setting",
    "No verified SLA published",
    "State realistic hours only if true",
    "S",
    "Low",
    "No false instant claims",
  ].join(","),
];

fs.writeFileSync(`${dir}/15-findings.csv`, findings.join("\n"), "utf8");
console.log("page rows", pageRows.length - 1, "findings", findings.length - 1);
